name: my first pipeline
on: push

jobs:
  greet: 
    runs-on: ubuntu-latest
    steps:
     - name: hello
       run: echo " welcome to my world of github actions"
     - name: hello 2
       run: echo " welcome to my world of github actions second"
  
