name: push to branch
on: 
  push:
    branches:
      -main

jobs:
  greet: 
    runs-on: ubuntu-latest
    steps:
     - name: push to branch intiated
       run: echo " welcome to my world of github actions"
     - name: push to branch
       run: echo " push to main branch success"
  
